name: kayak-strava-navbar S3 Deploy
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          

      - name: Build
        run: yarn build
        # env:
        #   REACT_APP_CLIENT_ID: ${{secrets.REACT_APP_CLIENT_ID}}
        #   REACT_APP_CLIENT_SECRET: ${{secrets.REACT_APP_CLIENT_SECRET}}
        #   REACT_APP_REDIRECT: ${{secrets.REACT_APP_REDIRECT}} 

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          filesToInclude: ".*/*,*/*,**"
